// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAJeKURMdW3dV1ee5xS9Uxjo1a5dorR_SU",
    appId: "1:687037020437:web:4194fde2e61bcf1e4e511c",
    messagingSenderId: "687037020437",
    projectId: "versionfinal-1c010",
    authDomain: "versionfinal-1c010.firebaseapp.com",
    storageBucket: "versionfinal-1c010.appspot.com",
    measurementId: "G-Z200NMQPVQ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqseE1WMssXwR72PKevhucMucIFz_SBc',
    appId: '1:1055019767750:android:6d92e038f1a9305b6c04c7',
    messagingSenderId: '687037020437',
    projectId: 'safa-pfe-project',
    storageBucket: 'safa-pfe-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4tHsmUKfad-XadQxIkM-8Xz6aHMVPhM',
    appId: '1:859050604457:ios:5515c583186d2254e5b6b8',
    messagingSenderId: '859050604457',
    projectId: 'mayssaapp-99975',
    storageBucket: 'mayssaapp-99975.appspot.com',
    iosBundleId: 'com.example.mayssaApp',
  );
}
